#!/usr/bin/env python3
"""Build Unwoke lockdown arrays from the stock flatpak.just snapshot."""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "files/upstream-snapshots/secureblue/flatpak.just"
DST = ROOT / "files/system/usr/share/unwoke/flatpak-lockdown-lists.sh"

MAP = {
    "kSharePermissions": "share",
    "kSocketPermissions": "socket",
    "kDevicePermissions": "device",
    "kFeaturePermissions": "feature",
    "kFilesystemPermissions": "filesystem",
    "kDangerousFilesystemPermissions": "dangerous",
    "kKnownSessionBusNames": "session",
    "kKnownSystemBusNames": "system",
}

ARRAY = re.compile(
    r"^\s*(k(?:Share|Socket|Device|Feature|Filesystem|DangerousFilesystem|KnownSessionBus|KnownSystemBus|FlatsealName)\w*)"
    r"\s*=\s*\((.*?)\)\s*$",
    re.M | re.S,
)


def bash_quote(item: str) -> str:
    return "'" + item.replace("'", "'\\''") + "'"


def parse_items(inner: str) -> list[str]:
    return re.findall(r'"([^"\\]*(?:\\.[^"\\]*)*)"', inner)


def main() -> int:
    text = SRC.read_text(encoding="utf-8")
    found: dict[str, list[str]] = {}
    for m in ARRAY.finditer(text):
        key, inner = m.group(1), m.group(2)
        if key not in MAP:
            continue
        items = parse_items(inner)
        if not items:
            print(f"empty array {key}", file=sys.stderr)
            return 1
        found[MAP[key]] = items
    missing = [v for v in MAP.values() if v not in found]
    if missing:
        print(f"missing arrays in snapshot: {missing}", file=sys.stderr)
        return 1
    lines = [
        "# Generated from files/upstream-snapshots/secureblue/flatpak.just",
        "# Do not edit. Regenerated by extract-flatpak-lockdown-lists.py",
        "",
    ]
    for name in ("share", "socket", "device", "feature", "filesystem", "dangerous", "session", "system"):
        quoted = " ".join(bash_quote(x) for x in found[name])
        lines.append(f"{name}=({quoted})")
        lines.append("")
    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {DST}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
