# Unwoke SecureBlue. Not affiliated. UNWOKE-SHIPPED-FIRST. Stock #1185.
# MIT License. Copyright (c) 2026 SeRgi270710267.
# NTS time sources. Revert: ujust set-nts off
server time.cloudflare.com iburst nts
server nts.ntp.se iburst nts
nocerttimecheck 1
