# Unwoke SecureBlue. Not affiliated with secureblue.
# MIT License. Copyright (c) 2026 SeRgi270710267.
# UNWOKE-SHIPPED-FIRST
# Generated from files/upstream-snapshots/secureblue/flatpak.just
# Do not edit. Regenerated by extract-flatpak-lockdown-lists.py

share=('network' 'ipc')

socket=('inherit-wayland-socket' 'gpg-agent' 'cups' 'pcsc' 'ssh-auth' 'system-bus' 'session-bus' 'pulseaudio' 'fallback-x11' 'x11')

device=('all' 'shm' 'kvm' 'input' 'usb')

feature=('per-app-dev-shm' 'canbus' 'bluetooth' 'multiarch' 'devel')

filesystem=('home' 'host-etc' 'host')

dangerous=('~/.bashrc' '~/.bash_profile' '/home' '/var/home' '/var' '/media' '/run/media' '/run' '/mnt')

session=('org.xfce.ScreenSaver' 'org.mate.ScreenSaver' 'org.cinnamon.ScreenSaver' 'org.gnome.ScreenSaver' 'org.kde.kwalletd6' 'org.gnome.Mutter.IdleMonitor.*' 'org.gnome.ControlCenter' 'org.gnome.Settings' 'org.gnome.SettingsDaemon.MediaKeys' 'org.gnome.SessionManager' 'org.gnome.Shell.Screenshot' 'org.kde.kiod5' 'org.kde.kwin.Screenshot' 'org.kde.JobViewServer' 'org.gtk.vfs.*' 'org.freedesktop.secrets' 'org.kde.kconfig.notify' 'org.kde.kpasswdserver' 'org.kde.*' 'org.kde.StatusNotifierWatcher' 'org.kde.kded6' 'org.kde.kpasswdserver6' 'org.kde.kiod6' 'com.canonical.Unity' 'org.freedesktop.Notifications' 'org.freedesktop.FileManager1' 'org.freedesktop.impl.portal.PermissionStore' 'org.freedesktop.Flatpak' 'com.canonical.AppMenu.Registrar' 'org.kde.KGlobalSettings' 'org.kde.kded5' 'com.canonical.Unity.LauncherEntry' 'org.kde.kwalletd5' 'org.gnome.SettingsDaemon' 'org.a11y.Bus' 'com.canonical.indicator.application' 'org.freedesktop.ScreenSaver' 'ca.desrt.dconf' 'org.freedesktop.PowerManagement' 'org.gnome.Software' 'org.freedesktop.Tracker3.Writeback' 'io.missioncenter.MissionCenter.Gatherer')

system=('org.bluez' 'org.freedesktop.home1' 'org.freedesktop.hostname1' 'org.freedesktop.import1' 'org.freedesktop.locale1' 'org.freedesktop.LogControl1' 'org.freedesktop.machine1' 'org.freedesktop.network1' 'org.freedesktop.oom1' 'org.freedesktop.portable1' 'org.freedesktop.resolve1' 'org.freedesktop.sysupdate1' 'org.freedesktop.timesync1' 'org.freedesktop.timedate1' 'org.freedesktop.systemd1' 'org.freedesktop.Avahi' 'org.freedesktop.Avahi.*' 'org.freedesktop.login1' 'org.freedesktop.NetworkManager' 'org.freedesktop.UPower' 'org.freedesktop.UDisks2' 'org.freedesktop.fwupd')
