# Unwoke SecureBlue. Not affiliated with secureblue.
# MIT License. Copyright (c) 2026 SeRgi270710267.
# UNWOKE-SHIPPED-FIRST
# NFS/CIFS client modules off until ujust set-network-fs on.
# Stock already masks nfs-server; this also blocks mounting shares.
# Revert: remove this file (network-fs.sh apply-boot).
blacklist nfs
blacklist nfsv3
blacklist nfsv4
blacklist nfsd
blacklist lockd
blacklist rpcrdma
blacklist cifs
blacklist smb3
install nfs /bin/true
install nfsv3 /bin/true
install nfsv4 /bin/true
install cifs /bin/true
