# Unwoke SecureBlue. Not affiliated with secureblue.
# MIT License. Copyright (c) 2026 SeRgi270710267.
# UNWOKE-SHIPPED-FIRST
# Unwoke: no Fedora/GNOME "am I online" HTTP check.
# Revert: ujust set-connectivity-check on
[connectivity]
enabled=false
uri=
