# Unwoke SecureBlue. Not affiliated with secureblue.
# MIT License. Copyright (c) 2026 SeRgi270710267.
# UNWOKE-SHIPPED-FIRST
# Unwoke: force Network Service Sandbox. Stock Trivalent leaves this off
# (chrome://settings/security) because it can clear cookies on exit.
# Revert: ujust set-trivalent-network-sandbox off
FEATURES+=",NetworkServiceSandbox"
