# Unwoke SecureBlue. Not affiliated with secureblue.
# MIT License. Copyright (c) 2026 SeRgi270710267.
# UNWOKE-SHIPPED-FIRST
# Unwoke isolation pack: disable WebGPU (policy covers WebGL).
# Revert: ujust set-brave-isolation off   (or set-trivalent-isolation off)
CHROMIUM_FLAGS+=" --disable-features=WebGPU,WebGPUService"
