# Unwoke SecureBlue. Not affiliated with secureblue.
# MIT License. Copyright (c) 2026 SeRgi270710267.
# UNWOKE-SHIPPED-FIRST
# Unwoke: extra Trivalent flags (optional hardening in their README).
# show-punycode-domains + clear-cross-origin-referrers. Some sites may break.
# Revert: ujust set-trivalent-referrers off
FEATURES+=",ShowPunycodeDomains,ClearCrossOriginReferrers"
